# CI to release the project for Linux, Windows, and macOS.

name: Release CI

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

env:
  PYTHON_VERSIONS: "3.10 3.11 3.12 3.13 3.14"

jobs:
  wheels:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.system || matrix.libc || 'windows' }}-${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS wheels
          - runner: macos-15-intel
            system: darwin
            target: x86_64
          - runner: macos-15
            system: darwin
            target: aarch64

          # Windows wheels
          - runner: windows-2022
            target: x86_64
          - runner: windows-11-arm
            target: aarch64

          # Manylinux wheels
          - runner: ubuntu-24.04
            libc: manylinux
            version: 2_28
            target: x86_64
          - runner: ubuntu-24.04-arm
            libc: manylinux
            version: 2_28
            target: aarch64

          # Musllinux wheels
          - runner: ubuntu-24.04
            libc: musllinux
            version: 1_2
            target: x86_64
          - runner: ubuntu-24.04-arm
            libc: musllinux
            version: 1_2
            target: aarch64
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Rust cache
        uses: actions/cache@v4
        with:
          path: target
          restore-keys: rust-${{ matrix.runner }}${{ matrix.libc && format('-{0}', matrix.libc) || '' }}
          key: rust-${{ matrix.runner }}${{ matrix.libc && format('-{0}', matrix.libc) || '' }}-${{ hashFiles('Cargo.lock') }}

      - name: Setup uv tool
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false

      - name: Setup Python
        shell: bash
        run: |
          os="${{ matrix.system || (matrix.libc && 'linux' || 'windows') }}-${{ matrix.target }}"
          v="${{ env.PYTHON_VERSIONS }}"; [[ $os == windows-aarch64 ]] && v=${v/3.10/}

          uv python install $(echo $v | sed "s/[^ ]*/&-$os/g")

          echo maturin="$(echo $v | xargs -n1 uv python find | sed 's/^/-i /' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: ${{matrix.libc }}_${{ matrix.version }}
          container: quay.io/pypa/${{matrix.libc }}_${{ matrix.version }}_${{ matrix.target }}:latest
          args: ${{ env.maturin }} --release --strip --out dist

      - name: Test wheels
        shell: bash
        run: |
          for v in ${{ env.PYTHON_VERSIONS }}; do
            (
              whl_path=$(realpath dist/robyn*cp$(echo $v | tr -d '.')*.whl)
              venv_dir="$RUNNER_TEMP/venv-$v"; uv venv --python $v "$venv_dir"

              cd $RUNNER_TEMP
              uv pip install --python "$venv_dir" --force-reinstall "$whl_path"
              uv run --python "$venv_dir" python -c "import robyn"
              rm -rf "$venv_dir"
            ) & done
          wait

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.libc || matrix.target }}-wheels
          path: dist/*.whl

  release:
    name: Releasing to PyPi
    runs-on: ubuntu-slim
    needs: [wheels]
    steps:
      - name: Download and merge all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Verify downloaded wheels
        run: ls -l dist/

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.3.2

      - name: Publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: uvx twine upload --skip-existing dist/*.whl
